/******************************************************************************/
// Bullfrog Engine Emulation Library - for use to remake classic games like
// Syndicate Wars, Magic Carpet, Genewars or Dungeon Keeper.
/******************************************************************************/
/** @file bfgentab.h
 *     Header file for ggengh.cpp and ggenf.cpp.
 * @par Purpose:
 *     Unknown.
 * @par Comment:
 *     None.
 * @author   Tomasz Lis
 * @date     12 Nov 2008 - 05 Nov 2021
 * @par  Copying and copyrights:
 *     This program is free software; you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation; either version 2 of the License, or
 *     (at your option) any later version.
 */
/******************************************************************************/
#ifndef BFLIBRARY_BFGENTAB_H_
#define BFLIBRARY_BFGENTAB_H_

#include "bftypes.h"

#ifdef __cplusplus
extern "C" {
#endif

extern TbPixel fade_table[256*64];
extern TbPixel ghost_table[256*256];

int LbFadeTableGenerate();

/** Load or generate colour ghosting table.
 *
 * Generates tables for ghosting between any two colors within given palette.
 * The tables simplify overlaying two colours, by storing 8-bit colour indexes
 * in an array.
 * Fills global ghost_table buffer with data from given file.
 * If the file access fails, the data is instead generated by computing closest
 * color indexes for ghosting.
 */
TbResult LbGhostTableGenerate(ubyte *pal, short intens, const char *fname);

/** Load colour ghosting table, making sure it is symmetrical.
 *
 * Loads colour table from disk, and then replaces diagonal half of the
 * array filling one triangle with corresponding colours ogf the other.
 * This maks the array return the came colour independently of source
 * colours order.
 */
TbResult LbGhostTableLoad(ubyte *pal, short intens, const char *fname);

#ifdef __cplusplus
};
#endif

#endif // BFLIBRARY_BFGENTAB_H_
/******************************************************************************/
