/******************************************************************************/
// Bullfrog Engine Emulation Library - for use to remake classic games like
// Syndicate Wars, Magic Carpet, Genewars or Dungeon Keeper.
/******************************************************************************/
/** @file bfgentab.h
 *     Header file for ggengh.cpp and ggenf.cpp.
 * @par Purpose:
 *     Unknown.
 * @par Comment:
 *     None.
 * @author   Tomasz Lis
 * @date     12 Nov 2008 - 05 Nov 2021
 * @par  Copying and copyrights:
 *     This program is free software; you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation; either version 2 of the License, or
 *     (at your option) any later version.
 */
/******************************************************************************/
#ifndef BFLIBRARY_BFGENTAB_H_
#define BFLIBRARY_BFGENTAB_H_

#include "bftypes.h"
#include "bfpalette.h"

#ifdef __cplusplus
extern "C" {
#endif

#pragma pack(1)

/** Colour tables, used for fading and merging colours in palette mode.
 *
 * In original assembly, these were separate arrays. But in order to
 * guarantee their position after each other in C, we need to define
 * them as a struct.
 */
struct TbColorTables {
  /** Table used for fading from black or increasing lightness. */
  TbPixel fade_table[PALETTE_FADE_LEVELS*PALETTE_8b_COLORS];
  /** Table used for ghosting (merging/overlaying two colors).
   * The specific compositing algorithm used may depend on application.
   */
  TbPixel ghost_table[PALETTE_8b_COLORS*PALETTE_8b_COLORS];
  TbPixel flat_colours_tl[2*PALETTE_8b_COLORS];
  TbPixel flat_colours_tr[2*PALETTE_8b_COLORS];
  TbPixel flat_colours_br[2*PALETTE_8b_COLORS];
  TbPixel flat_colours_bl[2*PALETTE_8b_COLORS];
  TbPixel robs_bollocks[PALETTE_8b_COLORS];
};

#pragma pack()

extern struct TbColorTables pixmap;

/** Generate colour transistion tables and save to file.
 *
 * Generates tables for fading colours and merging colours.
 * Fills global arrays within pixmap struct with generated colour
 * manipulation data.
 * Unlike other such functions, this one makes no tries to load
 * the file before generating all the colors.
 *
 * Some games have special, modified by hand color tables. Generating
 * the automatic colour table for these games may decrease image clarity,
 * as they may use perception-based colour matching and treat certain
 * colour indexes differently based on where these colours are used.
 */
TbResult LbColourTablesGenerate(const ubyte *palette, const TbPixel *unaffected,
  const char *fname);

/** Load colour transition tables from file.
 *
 * Reads tables for fading colours and merging colours from file.
 * Fills global arrays within pixmap struct with loaded colour
 * manipulation data.
 */
TbResult LbColourTablesLoad(const ubyte *palette, const char *fname);

/** Load or generate colour fading table.
 *
 * Generates table for fading any colour within given palette, to black.
 * The table simplify mixing each colour with black, storing PALETTE_FADE_LEVELS
 * of decreasing proportions in an array.
 * Fills global pixmap.fade_table buffer with data from given file.
 * If the file access fails, or file name is not provided, then the data is
 * instead generated by computing closest colour indexes for fading.
 */
TbResult LbFadeTableGenerate(const ubyte *palette, const TbPixel *unaffected,
  const char *fname);

/** Load colour fading table.
 *
 * This function loads only pixmap.fade_table from file. Consider storing and
 * loading the whole TbColorTables struct instead.
 */
TbResult LbFadeTableLoad(const ubyte *palette, const char *fname);

/** Load or generate extra colour ghosting table.
 *
 * Generates tables for ghosting between any two colours within given palette.
 * The table simplifies overlaying two colours, by storing 8-bit colour indexes
 * in an array.
 *
 * This function is for generating optional extra colour tables, in addtition
 * to the general table created by `LbExtraGhostTableGenerate()`. The resulted
 * table is not stored in any global variable, it is up to the creator to
 * properly using with functions which use colour mixing / transparency.
 *
 * Given table buffer is filled with data from given file.
 * If the file access fails, or file name is not provided, then the data is
 * instead generated by computing closest colour indexes for ghosting.
 *
 * @param pal Palette data to use for table generation.
 * @param mix_ratio Ratio between 1st and 2nd colour in the table, in percent;
 *   50% makes the table diagonally symmetrical.
 * @param intens_r Multiplicator for final red colour intensity; allows to hue whole table.
 * @param intens_g  Multiplicator for final green colour intensity.
 * @param intens_b Multiplicator for final green colour intensity.
 * @param table The table buffer to be filled.
 * @param fname Name of the file to store/load the table for speed optimization,
 *   or NULL if the data should be always generated from the palette.
 */
TbResult LbExtraGhostTableGenerate(const ubyte *pal, short mix_ratio,
  short intens_r, short intens_g, short intens_b, ubyte *table, const char *fname);

/** Load or generate colour ghosting table.
 *
 * Generates tables for ghosting between any two colours within given palette.
 * The table simplifies overlaying two colours, by storing 8-bit colour indexes
 * in an array.
 *
 * Fills global pixmap.ghost_table buffer with data from given file.
 * If the file access fails, or file name is not provided, then the data is
 * instead generated by computing closest colour indexes for ghosting.
 */
TbResult LbGhostTableGenerate(const ubyte *pal, short mix_ratio, const char *fname);

/** Load colour ghosting table, making sure it is symmetrical if at 50%.
 *
 * Loads colour table from disk. If requested mix ratio is 50%, it then
 * replaces diagonal half of the array, filling one triangle with corresponding
 * colours from the other triangle.
 * The diagonal copy makes the array return the same colour independently of
 * source colours order.
 *
 * This function loads only pixmap.ghost_table from file. Consider storing and
 * loading the whole TbColorTables struct instead.
 *
 * @param pal The palette which colour definitions are used.
 * @param mix_ratio Ratio of first-to-second colors weight, in percent.
 *        Value 100 means first colour only, 0 means second colour only.
 * @param fname File name from which the table is loaded.
 */
TbResult LbGhostTableLoad(const ubyte *pal, short mix_ratio, const char *fname);

#ifdef __cplusplus
};
#endif

#endif // BFLIBRARY_BFGENTAB_H_
/******************************************************************************/
